language: generic
addons:
  apt:
    packages:
      - zsh
before_install:
  - zsh --version
install:
  - (mkdir /tmp/urchin && cd /tmp/urchin && curl -s "$(curl -s https://registry.npmjs.com/urchin | grep -Eo '"tarball":\s*"[^"]+"' | tail -n 1 | awk -F\" '{ print $4 }')" -O && tar -x -f urchin*)
  - chmod +x /tmp/urchin/package/urchin
script:
  - /tmp/urchin/package/urchin -s zsh tests
